import { MLSAdapter } from "./adapter";
import {
  Property,
  PropertySearchParams,
  PropertySearchResult,
} from "./types";
import { generateSlug } from "@/lib/utils";

const MOCK_PROPERTIES: Property[] = [
  {
    mlsNumber: "MLS-100001",
    slug: "",
    address: "11342 N Alpine Hwy",
    city: "Highland",
    state: "UT",
    zipCode: "84003",
    price: 1250000,
    beds: 6,
    baths: 4.5,
    sqft: 5200,
    lotSize: "0.75 acres",
    yearBuilt: 2018,
    propertyType: "Single Family",
    status: "Active",
    description:
      "Stunning custom-built estate nestled against the Wasatch foothills in Highland. This home features soaring ceilings, a gourmet kitchen with double islands, and a walkout basement with a full theater room. Expansive views of Utah Lake and the valley below.",
    features: [
      "Gourmet Kitchen",
      "Home Theater",
      "Walkout Basement",
      "Mountain Views",
      "Smart Home System",
      "Heated Floors",
      "3-Car Garage",
      "RV Parking",
    ],
    images: [
      "/images/properties/property-1.svg",
      "/images/properties/property-2.svg",
      "/images/properties/property-3.svg",
      "/images/properties/property-4.svg",
      "/images/properties/property-5.svg",
    ],
    lat: 40.4274,
    lng: -111.7954,
    daysOnMarket: 12,
    garage: 3,
    stories: 2,
    listDate: "2026-02-19",
    agent: "David Childs",
  },
  {
    mlsNumber: "MLS-100002",
    slug: "",
    address: "5678 W Sunset Dr",
    city: "Alpine",
    state: "UT",
    zipCode: "84004",
    price: 1850000,
    beds: 7,
    baths: 5,
    sqft: 6800,
    lotSize: "1.2 acres",
    yearBuilt: 2020,
    propertyType: "Single Family",
    status: "Active",
    description:
      "Breathtaking Alpine luxury home on over an acre with panoramic mountain and valley views. Open-concept living with floor-to-ceiling windows, a chef's kitchen with Sub-Zero and Wolf appliances, and a resort-style backyard with heated pool and hot tub.",
    features: [
      "Heated Pool",
      "Hot Tub",
      "Chef's Kitchen",
      "Floor-to-Ceiling Windows",
      "Wine Cellar",
      "Home Office",
      "4-Car Garage",
      "Outdoor Kitchen",
    ],
    images: [
      "/images/properties/property-2.svg",
      "/images/properties/property-3.svg",
      "/images/properties/property-4.svg",
      "/images/properties/property-5.svg",
      "/images/properties/property-1.svg",
    ],
    lat: 40.4533,
    lng: -111.7738,
    daysOnMarket: 7,
    garage: 4,
    stories: 2,
    listDate: "2026-02-24",
    agent: "David Childs",
  },
  {
    mlsNumber: "MLS-100003",
    slug: "",
    address: "234 E 100 N",
    city: "American Fork",
    state: "UT",
    zipCode: "84003",
    price: 485000,
    beds: 4,
    baths: 2.5,
    sqft: 2400,
    lotSize: "0.22 acres",
    yearBuilt: 2005,
    propertyType: "Single Family",
    status: "Active",
    description:
      "Well-maintained family home in a quiet American Fork neighborhood close to schools and parks. Features an updated kitchen with granite countertops, a spacious master suite, and a fully fenced backyard with mature landscaping.",
    features: [
      "Granite Countertops",
      "Fenced Yard",
      "Central Air",
      "Updated Bathrooms",
      "Sprinkler System",
      "Storage Shed",
      "2-Car Garage",
    ],
    images: [
      "/images/properties/property-3.svg",
      "/images/properties/property-4.svg",
      "/images/properties/property-5.svg",
      "/images/properties/property-1.svg",
      "/images/properties/property-2.svg",
    ],
    lat: 40.3769,
    lng: -111.7953,
    daysOnMarket: 21,
    garage: 2,
    stories: 2,
    listDate: "2026-02-10",
    agent: "David Childs",
  },
  {
    mlsNumber: "MLS-100004",
    slug: "",
    address: "9012 N Cedar Ridge Ln",
    city: "Cedar Hills",
    state: "UT",
    zipCode: "84062",
    price: 725000,
    beds: 5,
    baths: 3.5,
    sqft: 3600,
    lotSize: "0.35 acres",
    yearBuilt: 2012,
    propertyType: "Single Family",
    status: "Active",
    description:
      "Beautiful Cedar Hills home backing up to the golf course with unobstructed mountain views. Features a main-level master suite, large bonus room, and a newly finished basement with kitchenette and separate entrance. Perfect for multi-generational living.",
    features: [
      "Golf Course Views",
      "Mother-in-Law Suite",
      "Main Level Master",
      "Bonus Room",
      "Kitchenette",
      "Covered Patio",
      "3-Car Garage",
      "Water Softener",
    ],
    images: [
      "/images/properties/property-4.svg",
      "/images/properties/property-5.svg",
      "/images/properties/property-1.svg",
      "/images/properties/property-2.svg",
      "/images/properties/property-3.svg",
    ],
    lat: 40.4136,
    lng: -111.7583,
    daysOnMarket: 5,
    garage: 3,
    stories: 2,
    listDate: "2026-02-26",
    agent: "David Childs",
  },
  {
    mlsNumber: "MLS-100005",
    slug: "",
    address: "3456 W Silicon Slopes Blvd",
    city: "Lehi",
    state: "UT",
    zipCode: "84043",
    price: 620000,
    beds: 4,
    baths: 3,
    sqft: 3100,
    lotSize: "0.18 acres",
    yearBuilt: 2021,
    propertyType: "Single Family",
    status: "Active",
    description:
      "Modern new-construction home in the heart of Lehi's tech corridor. Open floor plan with 10-foot ceilings, quartz countertops, and a spacious loft. Minutes from major employers, Thanksgiving Point, and I-15 access.",
    features: [
      "10-Foot Ceilings",
      "Quartz Countertops",
      "Loft Space",
      "Smart Thermostat",
      "Tankless Water Heater",
      "Patio",
      "2-Car Garage",
      "Energy Efficient",
    ],
    images: [
      "/images/properties/property-5.svg",
      "/images/properties/property-1.svg",
      "/images/properties/property-2.svg",
      "/images/properties/property-3.svg",
      "/images/properties/property-4.svg",
    ],
    lat: 40.3916,
    lng: -111.8508,
    daysOnMarket: 14,
    garage: 2,
    stories: 2,
    listDate: "2026-02-17",
    agent: "David Childs",
  },
  {
    mlsNumber: "MLS-100006",
    slug: "",
    address: "780 S 1200 E",
    city: "Orem",
    state: "UT",
    zipCode: "84097",
    price: 415000,
    beds: 3,
    baths: 2,
    sqft: 1850,
    lotSize: "0.19 acres",
    yearBuilt: 1998,
    propertyType: "Single Family",
    status: "Active",
    description:
      "Charming rambler in east Orem with easy access to the Bonneville Shoreline Trail. This home features vaulted ceilings, a cozy fireplace, and a large backyard perfect for entertaining. Close to UVU and BYU campuses.",
    features: [
      "Vaulted Ceilings",
      "Fireplace",
      "Large Backyard",
      "New Roof 2023",
      "Central Air",
      "Sprinkler System",
      "2-Car Garage",
    ],
    images: [
      "/images/properties/property-1.svg",
      "/images/properties/property-2.svg",
      "/images/properties/property-3.svg",
      "/images/properties/property-4.svg",
      "/images/properties/property-5.svg",
    ],
    lat: 40.2849,
    lng: -111.6677,
    daysOnMarket: 30,
    garage: 2,
    stories: 1,
    listDate: "2026-02-01",
    agent: "David Childs",
  },
  {
    mlsNumber: "MLS-100007",
    slug: "",
    address: "456 N University Ave",
    city: "Provo",
    state: "UT",
    zipCode: "84601",
    price: 359000,
    beds: 3,
    baths: 1.5,
    sqft: 1500,
    lotSize: "0.15 acres",
    yearBuilt: 1965,
    propertyType: "Single Family",
    status: "Active",
    description:
      "Classic Provo bungalow with vintage charm and modern updates. Refinished hardwood floors, updated electrical and plumbing, and a bright, sunny kitchen. Walking distance to downtown Provo restaurants and shops.",
    features: [
      "Hardwood Floors",
      "Updated Plumbing",
      "Updated Electrical",
      "Detached Garage",
      "Fruit Trees",
      "Walk to Downtown",
      "New Windows",
    ],
    images: [
      "/images/properties/property-2.svg",
      "/images/properties/property-3.svg",
      "/images/properties/property-4.svg",
      "/images/properties/property-5.svg",
      "/images/properties/property-1.svg",
    ],
    lat: 40.2338,
    lng: -111.6585,
    daysOnMarket: 45,
    garage: 1,
    stories: 1,
    listDate: "2026-01-17",
    agent: "David Childs",
  },
  {
    mlsNumber: "MLS-100008",
    slug: "",
    address: "1200 W 600 N",
    city: "Lindon",
    state: "UT",
    zipCode: "84042",
    price: 550000,
    beds: 4,
    baths: 3,
    sqft: 2800,
    lotSize: "0.28 acres",
    yearBuilt: 2010,
    propertyType: "Single Family",
    status: "Pending",
    description:
      "Spacious two-story home in a family-friendly Lindon neighborhood. Features a large kitchen island, formal dining room, and a finished basement with a wet bar. The oversized lot provides plenty of room for a future pool.",
    features: [
      "Kitchen Island",
      "Formal Dining",
      "Wet Bar",
      "Finished Basement",
      "Oversized Lot",
      "New HVAC",
      "3-Car Garage",
    ],
    images: [
      "/images/properties/property-3.svg",
      "/images/properties/property-4.svg",
      "/images/properties/property-5.svg",
      "/images/properties/property-1.svg",
      "/images/properties/property-2.svg",
    ],
    lat: 40.3437,
    lng: -111.7352,
    daysOnMarket: 18,
    garage: 3,
    stories: 2,
    listDate: "2026-02-13",
    agent: "David Childs",
  },
  {
    mlsNumber: "MLS-100009",
    slug: "",
    address: "890 N 100 E",
    city: "Pleasant Grove",
    state: "UT",
    zipCode: "84062",
    price: 475000,
    beds: 4,
    baths: 2.5,
    sqft: 2200,
    lotSize: "0.20 acres",
    yearBuilt: 2003,
    propertyType: "Single Family",
    status: "Active",
    description:
      "Well-kept Pleasant Grove home on a quiet street near the city recreation center. Open kitchen with breakfast nook, spacious bedrooms, and a large unfinished basement ready for your design. Enjoy the covered front porch and mountain views.",
    features: [
      "Breakfast Nook",
      "Covered Porch",
      "Mountain Views",
      "Unfinished Basement",
      "Central Vac",
      "Sprinkler System",
      "2-Car Garage",
    ],
    images: [
      "/images/properties/property-4.svg",
      "/images/properties/property-5.svg",
      "/images/properties/property-1.svg",
      "/images/properties/property-2.svg",
      "/images/properties/property-3.svg",
    ],
    lat: 40.3641,
    lng: -111.7385,
    daysOnMarket: 9,
    garage: 2,
    stories: 2,
    listDate: "2026-02-22",
    agent: "David Childs",
  },
  {
    mlsNumber: "MLS-100010",
    slug: "",
    address: "14500 S Traverse Ridge Rd",
    city: "Draper",
    state: "UT",
    zipCode: "84020",
    price: 1450000,
    beds: 6,
    baths: 5,
    sqft: 5800,
    lotSize: "0.50 acres",
    yearBuilt: 2019,
    propertyType: "Single Family",
    status: "Active",
    description:
      "Luxurious Draper estate in the exclusive Suncrest community with sweeping valley views. This home boasts a grand two-story entry, custom millwork throughout, and a backyard oasis with a waterfall pool. Minutes from skiing at Brighton and Snowbird.",
    features: [
      "Valley Views",
      "Custom Millwork",
      "Waterfall Pool",
      "Grand Entry",
      "Butler's Pantry",
      "Exercise Room",
      "4-Car Garage",
      "Security System",
    ],
    images: [
      "/images/properties/property-5.svg",
      "/images/properties/property-1.svg",
      "/images/properties/property-2.svg",
      "/images/properties/property-3.svg",
      "/images/properties/property-4.svg",
    ],
    lat: 40.5246,
    lng: -111.8463,
    daysOnMarket: 22,
    garage: 4,
    stories: 2,
    listDate: "2026-02-09",
    agent: "David Childs",
  },
  {
    mlsNumber: "MLS-100011",
    slug: "",
    address: "9200 S 1300 E",
    city: "Sandy",
    state: "UT",
    zipCode: "84094",
    price: 875000,
    beds: 5,
    baths: 3.5,
    sqft: 4100,
    lotSize: "0.30 acres",
    yearBuilt: 2015,
    propertyType: "Single Family",
    status: "Active",
    description:
      "Elegant Sandy home in a sought-after east-side neighborhood. Features an open great room with gas fireplace, a chef's kitchen with double ovens, and a fully finished basement with bedroom suite. Walking distance to Dimple Dell Recreation Area.",
    features: [
      "Gas Fireplace",
      "Double Ovens",
      "Finished Basement",
      "Master Suite",
      "Walk-In Closets",
      "Trex Deck",
      "3-Car Garage",
      "Smart Locks",
    ],
    images: [
      "/images/properties/property-1.svg",
      "/images/properties/property-2.svg",
      "/images/properties/property-3.svg",
      "/images/properties/property-4.svg",
      "/images/properties/property-5.svg",
    ],
    lat: 40.5667,
    lng: -111.8485,
    daysOnMarket: 16,
    garage: 3,
    stories: 2,
    listDate: "2026-02-15",
    agent: "David Childs",
  },
  {
    mlsNumber: "MLS-100012",
    slug: "",
    address: "352 E 200 S",
    city: "Salt Lake City",
    state: "UT",
    zipCode: "84111",
    price: 525000,
    beds: 2,
    baths: 2,
    sqft: 1400,
    lotSize: "N/A",
    yearBuilt: 2022,
    propertyType: "Condo",
    status: "Active",
    description:
      "Modern downtown Salt Lake City condo in the vibrant East Side district. Floor-to-ceiling windows with city and mountain views, luxury finishes, and a private balcony. Building amenities include rooftop lounge, fitness center, and concierge.",
    features: [
      "City Views",
      "Balcony",
      "Rooftop Lounge",
      "Fitness Center",
      "Concierge",
      "Underground Parking",
      "In-Unit Laundry",
      "Quartz Countertops",
    ],
    images: [
      "/images/properties/property-2.svg",
      "/images/properties/property-3.svg",
      "/images/properties/property-4.svg",
      "/images/properties/property-5.svg",
      "/images/properties/property-1.svg",
    ],
    lat: 40.7608,
    lng: -111.8761,
    daysOnMarket: 8,
    hoaFees: 450,
    garage: 1,
    stories: 1,
    listDate: "2026-02-23",
    agent: "David Childs",
  },
  {
    mlsNumber: "MLS-100013",
    slug: "",
    address: "2345 N Redwood Rd",
    city: "Saratoga Springs",
    state: "UT",
    zipCode: "84045",
    price: 565000,
    beds: 5,
    baths: 3,
    sqft: 3200,
    lotSize: "0.20 acres",
    yearBuilt: 2022,
    propertyType: "Single Family",
    status: "Active",
    description:
      "Nearly new Saratoga Springs home in the popular Harvest Hills community. Open floor plan with a modern farmhouse aesthetic, shiplap accents, and a large mudroom. Close to Utah Lake, parks, and the new commercial center.",
    features: [
      "Farmhouse Style",
      "Shiplap Accents",
      "Mudroom",
      "Walk-In Pantry",
      "LVP Flooring",
      "Patio",
      "2-Car Garage",
      "Community Pool",
    ],
    images: [
      "/images/properties/property-3.svg",
      "/images/properties/property-4.svg",
      "/images/properties/property-5.svg",
      "/images/properties/property-1.svg",
      "/images/properties/property-2.svg",
    ],
    lat: 40.3493,
    lng: -111.9047,
    daysOnMarket: 11,
    hoaFees: 85,
    garage: 2,
    stories: 2,
    listDate: "2026-02-20",
    agent: "David Childs",
  },
  {
    mlsNumber: "MLS-100014",
    slug: "",
    address: "6789 N Eagle Mountain Blvd",
    city: "Eagle Mountain",
    state: "UT",
    zipCode: "84005",
    price: 425000,
    beds: 4,
    baths: 2.5,
    sqft: 2500,
    lotSize: "0.15 acres",
    yearBuilt: 2023,
    propertyType: "Single Family",
    status: "Active",
    description:
      "Affordable new construction in Eagle Mountain with mountain views and wide-open skies. Features a bright open floor plan, stainless steel appliances, and a spacious backyard. Easy access to Pony Express Parkway and Camp Williams.",
    features: [
      "New Construction",
      "Mountain Views",
      "Stainless Appliances",
      "Central Air",
      "Full Landscaping",
      "Patio",
      "2-Car Garage",
      "Community Park",
    ],
    images: [
      "/images/properties/property-4.svg",
      "/images/properties/property-5.svg",
      "/images/properties/property-1.svg",
      "/images/properties/property-2.svg",
      "/images/properties/property-3.svg",
    ],
    lat: 40.3141,
    lng: -111.9808,
    daysOnMarket: 19,
    hoaFees: 55,
    garage: 2,
    stories: 2,
    listDate: "2026-02-12",
    agent: "David Childs",
  },
  {
    mlsNumber: "MLS-100015",
    slug: "",
    address: "1100 E Canyon Rd",
    city: "Spanish Fork",
    state: "UT",
    zipCode: "84660",
    price: 510000,
    beds: 5,
    baths: 3,
    sqft: 2900,
    lotSize: "0.25 acres",
    yearBuilt: 2016,
    propertyType: "Single Family",
    status: "Sold",
    description:
      "Beautiful two-story in Spanish Fork Canyon foothills with a sprawling yard and stunning canyon views. Features a fully finished basement, large master walk-in closet, and a covered deck perfect for summer BBQs.",
    features: [
      "Canyon Views",
      "Finished Basement",
      "Walk-In Closet",
      "Covered Deck",
      "Sprinkler System",
      "Fruit Trees",
      "3-Car Garage",
      "Gas Range",
    ],
    images: [
      "/images/properties/property-5.svg",
      "/images/properties/property-1.svg",
      "/images/properties/property-2.svg",
      "/images/properties/property-3.svg",
      "/images/properties/property-4.svg",
    ],
    lat: 40.1149,
    lng: -111.6308,
    daysOnMarket: 60,
    garage: 3,
    stories: 2,
    listDate: "2026-01-02",
    agent: "David Childs",
  },
  {
    mlsNumber: "MLS-100016",
    slug: "",
    address: "400 S 400 W",
    city: "Springville",
    state: "UT",
    zipCode: "84663",
    price: 390000,
    beds: 3,
    baths: 2,
    sqft: 1700,
    lotSize: "0.18 acres",
    yearBuilt: 1992,
    propertyType: "Single Family",
    status: "Active",
    description:
      "Cozy Springville rambler near the historic Art City downtown area. Recently updated with new paint, carpet, and fixtures throughout. Enjoy a large covered patio and a fully fenced yard with garden space.",
    features: [
      "New Paint",
      "New Carpet",
      "Covered Patio",
      "Fenced Yard",
      "Garden Space",
      "Central Air",
      "2-Car Garage",
    ],
    images: [
      "/images/properties/property-1.svg",
      "/images/properties/property-2.svg",
      "/images/properties/property-3.svg",
      "/images/properties/property-4.svg",
      "/images/properties/property-5.svg",
    ],
    lat: 40.1652,
    lng: -111.6149,
    daysOnMarket: 25,
    garage: 2,
    stories: 1,
    listDate: "2026-02-06",
    agent: "David Childs",
  },
  {
    mlsNumber: "MLS-100017",
    slug: "",
    address: "1500 S Mapleton Ln",
    city: "Mapleton",
    state: "UT",
    zipCode: "84664",
    price: 950000,
    beds: 6,
    baths: 4,
    sqft: 4500,
    lotSize: "0.65 acres",
    yearBuilt: 2014,
    propertyType: "Single Family",
    status: "Active",
    description:
      "Impressive Mapleton estate on a sprawling lot with incredible mountain views. This home features a grand kitchen with custom cabinetry, a theater room, and an oversized bonus room. Horse property potential with irrigated pasture.",
    features: [
      "Horse Property",
      "Custom Cabinetry",
      "Theater Room",
      "Bonus Room",
      "Irrigated Pasture",
      "Mountain Views",
      "4-Car Garage",
      "RV Parking",
    ],
    images: [
      "/images/properties/property-2.svg",
      "/images/properties/property-3.svg",
      "/images/properties/property-4.svg",
      "/images/properties/property-5.svg",
      "/images/properties/property-1.svg",
    ],
    lat: 40.1369,
    lng: -111.5793,
    daysOnMarket: 33,
    garage: 4,
    stories: 2,
    listDate: "2026-01-29",
    agent: "David Childs",
  },
  {
    mlsNumber: "MLS-100018",
    slug: "",
    address: "7890 S Highland Dr",
    city: "Sandy",
    state: "UT",
    zipCode: "84093",
    price: 699000,
    beds: 4,
    baths: 3,
    sqft: 3400,
    lotSize: "0.25 acres",
    yearBuilt: 2008,
    propertyType: "Single Family",
    status: "Pending",
    description:
      "Move-in ready Sandy home in the desirable Willow Creek neighborhood. Gourmet kitchen with Viking range, hardwood floors on the main level, and a professionally landscaped yard with putting green. Top-rated Canyons School District.",
    features: [
      "Viking Range",
      "Hardwood Floors",
      "Putting Green",
      "Professional Landscaping",
      "Crown Molding",
      "Wainscoting",
      "3-Car Garage",
    ],
    images: [
      "/images/properties/property-3.svg",
      "/images/properties/property-4.svg",
      "/images/properties/property-5.svg",
      "/images/properties/property-1.svg",
      "/images/properties/property-2.svg",
    ],
    lat: 40.5752,
    lng: -111.8219,
    daysOnMarket: 10,
    garage: 3,
    stories: 2,
    listDate: "2026-02-21",
    agent: "David Childs",
  },
  {
    mlsNumber: "MLS-100019",
    slug: "",
    address: "100 W Center St Unit 504",
    city: "Provo",
    state: "UT",
    zipCode: "84601",
    price: 375000,
    beds: 2,
    baths: 2,
    sqft: 1200,
    lotSize: "N/A",
    yearBuilt: 2021,
    propertyType: "Condo",
    status: "Active",
    description:
      "Stylish downtown Provo condo with stunning views of the Wasatch Range. Modern open layout with a gourmet kitchen, spa-like bathroom, and a private balcony. Steps from Center Street dining, nightlife, and the Provo City Temple.",
    features: [
      "Mountain Views",
      "Balcony",
      "Modern Kitchen",
      "Spa Bathroom",
      "In-Unit Laundry",
      "Secure Entry",
      "Elevator",
      "Assigned Parking",
    ],
    images: [
      "/images/properties/property-4.svg",
      "/images/properties/property-5.svg",
      "/images/properties/property-1.svg",
      "/images/properties/property-2.svg",
      "/images/properties/property-3.svg",
    ],
    lat: 40.2338,
    lng: -111.6608,
    daysOnMarket: 15,
    hoaFees: 325,
    garage: 1,
    stories: 1,
    listDate: "2026-02-16",
    agent: "David Childs",
  },
  {
    mlsNumber: "MLS-100020",
    slug: "",
    address: "2200 N Canyon Rd",
    city: "Highland",
    state: "UT",
    zipCode: "84003",
    price: 985000,
    beds: 5,
    baths: 4,
    sqft: 4800,
    lotSize: "0.55 acres",
    yearBuilt: 2016,
    propertyType: "Single Family",
    status: "Active",
    description:
      "Gorgeous Highland home on a premium half-acre lot with mountain views. Spacious open floor plan with a two-story great room, gourmet kitchen, and luxurious master suite. The finished walkout basement includes a rec room and guest quarters.",
    features: [
      "Two-Story Great Room",
      "Gourmet Kitchen",
      "Walkout Basement",
      "Guest Quarters",
      "Rec Room",
      "Covered Deck",
      "3-Car Garage",
      "Mountain Views",
    ],
    images: [
      "/images/properties/property-5.svg",
      "/images/properties/property-1.svg",
      "/images/properties/property-2.svg",
      "/images/properties/property-3.svg",
      "/images/properties/property-4.svg",
    ],
    lat: 40.4310,
    lng: -111.7802,
    daysOnMarket: 6,
    garage: 3,
    stories: 2,
    listDate: "2026-02-25",
    agent: "David Childs",
  },
  {
    mlsNumber: "MLS-100021",
    slug: "",
    address: "345 E 800 N",
    city: "Lehi",
    state: "UT",
    zipCode: "84043",
    price: 469000,
    beds: 3,
    baths: 2.5,
    sqft: 2100,
    lotSize: "0.14 acres",
    yearBuilt: 2019,
    propertyType: "Townhouse",
    status: "Active",
    description:
      "Modern Lehi townhome in the Holbrook Farms community with low-maintenance living. Features an open main level, quartz countertops, and a private fenced patio. Community amenities include pool, clubhouse, and playground.",
    features: [
      "Quartz Countertops",
      "Private Patio",
      "Community Pool",
      "Clubhouse",
      "Playground",
      "LVP Flooring",
      "2-Car Garage",
      "Smart Home",
    ],
    images: [
      "/images/properties/property-1.svg",
      "/images/properties/property-2.svg",
      "/images/properties/property-3.svg",
      "/images/properties/property-4.svg",
      "/images/properties/property-5.svg",
    ],
    lat: 40.3917,
    lng: -111.8306,
    daysOnMarket: 20,
    hoaFees: 195,
    garage: 2,
    stories: 2,
    listDate: "2026-02-11",
    agent: "David Childs",
  },
  {
    mlsNumber: "MLS-100022",
    slug: "",
    address: "6543 W Oquirrh Mountain Dr",
    city: "Salt Lake City",
    state: "UT",
    zipCode: "84118",
    price: 445000,
    beds: 4,
    baths: 2,
    sqft: 2000,
    lotSize: "0.20 acres",
    yearBuilt: 2001,
    propertyType: "Single Family",
    status: "Sold",
    description:
      "Solid west-side Salt Lake City home with Oquirrh Mountain views. Updated kitchen with subway tile backsplash, new flooring throughout, and a large family room in the basement. Close to Utah Olympic Oval and Valley Fair Mall.",
    features: [
      "Updated Kitchen",
      "Subway Tile",
      "New Flooring",
      "Family Room",
      "Finished Basement",
      "Fenced Yard",
      "2-Car Garage",
    ],
    images: [
      "/images/properties/property-2.svg",
      "/images/properties/property-3.svg",
      "/images/properties/property-4.svg",
      "/images/properties/property-5.svg",
      "/images/properties/property-1.svg",
    ],
    lat: 40.6461,
    lng: -111.9681,
    daysOnMarket: 50,
    garage: 2,
    stories: 2,
    listDate: "2026-01-12",
    agent: "David Childs",
  },
  {
    mlsNumber: "MLS-100023",
    slug: "",
    address: "800 W 1600 N",
    city: "Orem",
    state: "UT",
    zipCode: "84057",
    price: 399000,
    beds: 4,
    baths: 2,
    sqft: 1900,
    lotSize: "0.17 acres",
    yearBuilt: 1996,
    propertyType: "Single Family",
    status: "Active",
    description:
      "Affordable Orem split-entry in a well-established neighborhood near Scera Park. Features an updated kitchen, two living areas, and a fenced backyard with a trampoline-ready flat section. Close to Orem Owlz ballpark and the Frontrunner station.",
    features: [
      "Updated Kitchen",
      "Two Living Areas",
      "Fenced Yard",
      "New Water Heater",
      "Central Air",
      "Ceiling Fans",
      "2-Car Garage",
    ],
    images: [
      "/images/properties/property-3.svg",
      "/images/properties/property-4.svg",
      "/images/properties/property-5.svg",
      "/images/properties/property-1.svg",
      "/images/properties/property-2.svg",
    ],
    lat: 40.3113,
    lng: -111.7128,
    daysOnMarket: 28,
    garage: 2,
    stories: 2,
    listDate: "2026-02-03",
    agent: "David Childs",
  },
  {
    mlsNumber: "MLS-100024",
    slug: "",
    address: "3200 E Traverse Mountain Blvd",
    city: "Lehi",
    state: "UT",
    zipCode: "84043",
    price: 890000,
    beds: 5,
    baths: 4,
    sqft: 4200,
    lotSize: "0.30 acres",
    yearBuilt: 2017,
    propertyType: "Single Family",
    status: "Active",
    description:
      "Spectacular Traverse Mountain home with 360-degree views from the valley to the peaks. Open main-level living with a designer kitchen, office, and guest suite. Lower level features a home gym, media room, and large storage. Minutes from Thanksgiving Point.",
    features: [
      "360 Views",
      "Designer Kitchen",
      "Home Gym",
      "Media Room",
      "Guest Suite",
      "Home Office",
      "3-Car Garage",
      "Tankless Water Heater",
    ],
    images: [
      "/images/properties/property-4.svg",
      "/images/properties/property-5.svg",
      "/images/properties/property-1.svg",
      "/images/properties/property-2.svg",
      "/images/properties/property-3.svg",
    ],
    lat: 40.4218,
    lng: -111.8124,
    daysOnMarket: 13,
    garage: 3,
    stories: 2,
    listDate: "2026-02-18",
    agent: "David Childs",
  },
  {
    mlsNumber: "MLS-100025",
    slug: "",
    address: "456 E State St",
    city: "American Fork",
    state: "UT",
    zipCode: "84003",
    price: 375000,
    beds: 3,
    baths: 2,
    sqft: 1600,
    lotSize: "0.16 acres",
    yearBuilt: 1985,
    propertyType: "Single Family",
    status: "Coming Soon",
    description:
      "Darling American Fork starter home with a large lot and mature trees. Updated bathroom, new furnace, and a bright open living area. Walking distance to Robinson Park and American Fork Steel Days festivities.",
    features: [
      "Mature Trees",
      "New Furnace",
      "Updated Bathroom",
      "Large Lot",
      "Covered Porch",
      "Central Air",
      "1-Car Garage",
    ],
    images: [
      "/images/properties/property-5.svg",
      "/images/properties/property-1.svg",
      "/images/properties/property-2.svg",
      "/images/properties/property-3.svg",
      "/images/properties/property-4.svg",
    ],
    lat: 40.3776,
    lng: -111.7886,
    daysOnMarket: 0,
    garage: 1,
    stories: 1,
    listDate: "2026-03-03",
    agent: "David Childs",
  },
  {
    mlsNumber: "MLS-100026",
    slug: "",
    address: "10200 S 1300 E Unit 301",
    city: "Sandy",
    state: "UT",
    zipCode: "84094",
    price: 395000,
    beds: 2,
    baths: 2,
    sqft: 1300,
    lotSize: "N/A",
    yearBuilt: 2020,
    propertyType: "Condo",
    status: "Active",
    description:
      "Sleek Sandy condo in the South Towne corridor with easy access to shopping and entertainment. Open floor plan with premium finishes, a spacious balcony, and secure underground parking. Building includes a gym and community room.",
    features: [
      "Premium Finishes",
      "Balcony",
      "Underground Parking",
      "Gym Access",
      "Community Room",
      "In-Unit Laundry",
      "Quartz Countertops",
      "EV Charging",
    ],
    images: [
      "/images/properties/property-1.svg",
      "/images/properties/property-2.svg",
      "/images/properties/property-3.svg",
      "/images/properties/property-4.svg",
      "/images/properties/property-5.svg",
    ],
    lat: 40.5581,
    lng: -111.8485,
    daysOnMarket: 17,
    hoaFees: 375,
    garage: 1,
    stories: 1,
    listDate: "2026-02-14",
    agent: "David Childs",
  },
  {
    mlsNumber: "MLS-100027",
    slug: "",
    address: "1100 N Palisade Dr",
    city: "Orem",
    state: "UT",
    zipCode: "84097",
    price: 720000,
    beds: 5,
    baths: 3.5,
    sqft: 3500,
    lotSize: "0.30 acres",
    yearBuilt: 2011,
    propertyType: "Single Family",
    status: "Active",
    description:
      "Exceptional east Orem home perched above the city with sweeping views of Utah Lake. Features a bright white kitchen, spacious master with ensuite spa bath, and a lower-level family room with walkout. Community trail access right from your backyard.",
    features: [
      "Lake Views",
      "White Kitchen",
      "Spa Bath",
      "Walkout Basement",
      "Trail Access",
      "Gas Fireplace",
      "3-Car Garage",
      "Central Vac",
    ],
    images: [
      "/images/properties/property-2.svg",
      "/images/properties/property-3.svg",
      "/images/properties/property-4.svg",
      "/images/properties/property-5.svg",
      "/images/properties/property-1.svg",
    ],
    lat: 40.3050,
    lng: -111.6618,
    daysOnMarket: 4,
    garage: 3,
    stories: 2,
    listDate: "2026-02-27",
    agent: "David Childs",
  },
  {
    mlsNumber: "MLS-100028",
    slug: "",
    address: "2100 W Main St",
    city: "Lehi",
    state: "UT",
    zipCode: "84043",
    price: 535000,
    beds: 4,
    baths: 2.5,
    sqft: 2600,
    lotSize: "0.18 acres",
    yearBuilt: 2020,
    propertyType: "Single Family",
    status: "Pending",
    description:
      "Newer Lehi home in the Wines Park community with a thoughtful floor plan. Upgraded finishes include soft-close cabinets, undermount sinks, and tile showers. The flex room on the main level can serve as an office or playroom.",
    features: [
      "Soft-Close Cabinets",
      "Tile Showers",
      "Flex Room",
      "Undermount Sinks",
      "Full Landscaping",
      "Patio",
      "2-Car Garage",
      "Playground Nearby",
    ],
    images: [
      "/images/properties/property-3.svg",
      "/images/properties/property-4.svg",
      "/images/properties/property-5.svg",
      "/images/properties/property-1.svg",
      "/images/properties/property-2.svg",
    ],
    lat: 40.3872,
    lng: -111.8623,
    daysOnMarket: 23,
    hoaFees: 65,
    garage: 2,
    stories: 2,
    listDate: "2026-02-08",
    agent: "David Childs",
  },
  {
    mlsNumber: "MLS-100029",
    slug: "",
    address: "5500 W 11800 S",
    city: "Draper",
    state: "UT",
    zipCode: "84020",
    price: 750000,
    beds: 5,
    baths: 3,
    sqft: 3700,
    lotSize: "0.28 acres",
    yearBuilt: 2013,
    propertyType: "Single Family",
    status: "Active",
    description:
      "Attractive Draper home in Hidden Canyon Estates with a beautiful mountain backdrop. Vaulted ceilings in the living room, a gourmet kitchen with granite island, and a fully finished basement with built-in bookshelves. The backyard features a pergola and fire pit.",
    features: [
      "Vaulted Ceilings",
      "Granite Island",
      "Built-In Bookshelves",
      "Pergola",
      "Fire Pit",
      "Finished Basement",
      "3-Car Garage",
      "Sprinkler System",
    ],
    images: [
      "/images/properties/property-4.svg",
      "/images/properties/property-5.svg",
      "/images/properties/property-1.svg",
      "/images/properties/property-2.svg",
      "/images/properties/property-3.svg",
    ],
    lat: 40.5187,
    lng: -111.8782,
    daysOnMarket: 27,
    garage: 3,
    stories: 2,
    listDate: "2026-02-04",
    agent: "David Childs",
  },
  {
    mlsNumber: "MLS-100030",
    slug: "",
    address: "400 N 200 W",
    city: "Alpine",
    state: "UT",
    zipCode: "84004",
    price: 1100000,
    beds: 5,
    baths: 4,
    sqft: 4600,
    lotSize: "0.80 acres",
    yearBuilt: 2009,
    propertyType: "Single Family",
    status: "Active",
    description:
      "Stately Alpine home on a large wooded lot with a private feel. Soaring ceilings with exposed beams, a stone fireplace, and a sun-drenched conservatory. The sprawling backyard includes a sport court and garden greenhouse.",
    features: [
      "Exposed Beams",
      "Stone Fireplace",
      "Conservatory",
      "Sport Court",
      "Greenhouse",
      "Wooded Lot",
      "3-Car Garage",
      "Circular Drive",
    ],
    images: [
      "/images/properties/property-5.svg",
      "/images/properties/property-1.svg",
      "/images/properties/property-2.svg",
      "/images/properties/property-3.svg",
      "/images/properties/property-4.svg",
    ],
    lat: 40.4617,
    lng: -111.7687,
    daysOnMarket: 38,
    garage: 3,
    stories: 2,
    listDate: "2026-01-24",
    agent: "David Childs",
  },
  {
    mlsNumber: "MLS-100031",
    slug: "",
    address: "678 S Geneva Rd",
    city: "Orem",
    state: "UT",
    zipCode: "84058",
    price: 362000,
    beds: 3,
    baths: 2,
    sqft: 1450,
    lotSize: "0.13 acres",
    yearBuilt: 1988,
    propertyType: "Single Family",
    status: "Active",
    description:
      "Great-value Orem home near the lakefront with easy access to I-15 and UVU. Updated flooring and light fixtures throughout, with a cozy family room and an attached single-car garage. The backyard is low-maintenance with artificial turf.",
    features: [
      "Updated Flooring",
      "New Light Fixtures",
      "Artificial Turf",
      "Low Maintenance",
      "Central Air",
      "1-Car Garage",
      "Close to UVU",
    ],
    images: [
      "/images/properties/property-1.svg",
      "/images/properties/property-2.svg",
      "/images/properties/property-3.svg",
      "/images/properties/property-4.svg",
      "/images/properties/property-5.svg",
    ],
    lat: 40.2791,
    lng: -111.7381,
    daysOnMarket: 35,
    garage: 1,
    stories: 1,
    listDate: "2026-01-27",
    agent: "David Childs",
  },
  {
    mlsNumber: "MLS-100032",
    slug: "",
    address: "9050 S 3100 E",
    city: "Sandy",
    state: "UT",
    zipCode: "84093",
    price: 1350000,
    beds: 6,
    baths: 5,
    sqft: 5500,
    lotSize: "0.42 acres",
    yearBuilt: 2021,
    propertyType: "Single Family",
    status: "Active",
    description:
      "Magnificent custom Sandy home in the exclusive Pepperwood neighborhood. Features a grand foyer with floating staircase, a chef's kitchen with Thermador appliances, and a resort-style pool with swim-up bar. Minutes from Big and Little Cottonwood canyons.",
    features: [
      "Floating Staircase",
      "Thermador Appliances",
      "Swim-Up Bar",
      "Resort Pool",
      "Smart Home",
      "Custom Closets",
      "4-Car Garage",
      "Ski Storage",
    ],
    images: [
      "/images/properties/property-2.svg",
      "/images/properties/property-3.svg",
      "/images/properties/property-4.svg",
      "/images/properties/property-5.svg",
      "/images/properties/property-1.svg",
    ],
    lat: 40.5712,
    lng: -111.8103,
    daysOnMarket: 3,
    garage: 4,
    stories: 2,
    listDate: "2026-02-28",
    agent: "David Childs",
  },
  {
    mlsNumber: "MLS-100033",
    slug: "",
    address: "250 N Main St",
    city: "Cedar Hills",
    state: "UT",
    zipCode: "84062",
    price: 599000,
    beds: 4,
    baths: 3,
    sqft: 2900,
    lotSize: "0.25 acres",
    yearBuilt: 2007,
    propertyType: "Single Family",
    status: "Active",
    description:
      "Well-designed Cedar Hills home adjacent to the community park and walking trails. Features an open kitchen with center island, spacious bedrooms, and a fully finished basement with a craft room and storage. The backyard boasts a stamped concrete patio and pergola.",
    features: [
      "Center Island",
      "Craft Room",
      "Stamped Concrete",
      "Pergola",
      "Park Adjacent",
      "Walking Trails",
      "2-Car Garage",
      "New Roof",
    ],
    images: [
      "/images/properties/property-3.svg",
      "/images/properties/property-4.svg",
      "/images/properties/property-5.svg",
      "/images/properties/property-1.svg",
      "/images/properties/property-2.svg",
    ],
    lat: 40.4164,
    lng: -111.7518,
    daysOnMarket: 14,
    garage: 2,
    stories: 2,
    listDate: "2026-02-17",
    agent: "David Childs",
  },
  {
    mlsNumber: "MLS-100034",
    slug: "",
    address: "3456 N Thanksgiving Way",
    city: "Lehi",
    state: "UT",
    zipCode: "84043",
    price: 715000,
    beds: 5,
    baths: 3.5,
    sqft: 3500,
    lotSize: "0.22 acres",
    yearBuilt: 2018,
    propertyType: "Single Family",
    status: "Active",
    description:
      "Premier Lehi home steps from Thanksgiving Point gardens and museum. Tastefully upgraded with white shaker cabinets, marble counters, and designer light fixtures. The spacious master suite includes a soaking tub and walk-in tile shower.",
    features: [
      "White Shaker Cabinets",
      "Marble Counters",
      "Designer Lighting",
      "Soaking Tub",
      "Tile Shower",
      "Near Thanksgiving Point",
      "3-Car Garage",
      "Full Landscape",
    ],
    images: [
      "/images/properties/property-4.svg",
      "/images/properties/property-5.svg",
      "/images/properties/property-1.svg",
      "/images/properties/property-2.svg",
      "/images/properties/property-3.svg",
    ],
    lat: 40.4056,
    lng: -111.8291,
    daysOnMarket: 11,
    garage: 3,
    stories: 2,
    listDate: "2026-02-20",
    agent: "David Childs",
  },
  {
    mlsNumber: "MLS-100035",
    slug: "",
    address: "1800 N State St Unit 12",
    city: "Provo",
    state: "UT",
    zipCode: "84604",
    price: 289000,
    beds: 2,
    baths: 1.5,
    sqft: 1050,
    lotSize: "N/A",
    yearBuilt: 2015,
    propertyType: "Townhouse",
    status: "Active",
    description:
      "Affordable Provo townhome ideal for students, young professionals, or investors. Modern interior with granite counters, stainless appliances, and an attached one-car garage. Close to BYU campus and Provo Towne Centre.",
    features: [
      "Granite Counters",
      "Stainless Appliances",
      "Attached Garage",
      "Close to BYU",
      "Vaulted Ceilings",
      "Patio",
      "Community Park",
    ],
    images: [
      "/images/properties/property-5.svg",
      "/images/properties/property-1.svg",
      "/images/properties/property-2.svg",
      "/images/properties/property-3.svg",
      "/images/properties/property-4.svg",
    ],
    lat: 40.2536,
    lng: -111.6521,
    daysOnMarket: 42,
    hoaFees: 175,
    garage: 1,
    stories: 2,
    listDate: "2026-01-20",
    agent: "David Childs",
  },
  {
    mlsNumber: "MLS-100036",
    slug: "",
    address: "4567 W Harvest Moon Dr",
    city: "Saratoga Springs",
    state: "UT",
    zipCode: "84045",
    price: 495000,
    beds: 4,
    baths: 2.5,
    sqft: 2700,
    lotSize: "0.16 acres",
    yearBuilt: 2023,
    propertyType: "Single Family",
    status: "Active",
    description:
      "Brand-new Saratoga Springs home in the Galley's Landing community with lake access. Bright and airy layout with 9-foot ceilings, a spacious kitchen pantry, and a dedicated mudroom. Enjoy the community splash pad, playground, and walking paths.",
    features: [
      "9-Foot Ceilings",
      "Walk-In Pantry",
      "Mudroom",
      "Lake Access",
      "Splash Pad",
      "Walking Paths",
      "2-Car Garage",
      "Smart Thermostat",
    ],
    images: [
      "/images/properties/property-1.svg",
      "/images/properties/property-2.svg",
      "/images/properties/property-3.svg",
      "/images/properties/property-4.svg",
      "/images/properties/property-5.svg",
    ],
    lat: 40.3580,
    lng: -111.9162,
    daysOnMarket: 8,
    hoaFees: 95,
    garage: 2,
    stories: 2,
    listDate: "2026-02-23",
    agent: "David Childs",
  },
  {
    mlsNumber: "MLS-100037",
    slug: "",
    address: "7890 N Silver Lake Dr",
    city: "Eagle Mountain",
    state: "UT",
    zipCode: "84005",
    price: 399000,
    beds: 3,
    baths: 2.5,
    sqft: 2100,
    lotSize: "0.14 acres",
    yearBuilt: 2024,
    propertyType: "Townhouse",
    status: "Active",
    description:
      "Stylish Eagle Mountain townhome in the brand-new Silver Lake development. End unit with extra windows and natural light, modern finishes throughout, and a low-maintenance yard. Community features include a pool, trails, and a dog park.",
    features: [
      "End Unit",
      "Extra Windows",
      "Modern Finishes",
      "Community Pool",
      "Dog Park",
      "Trails",
      "2-Car Garage",
      "Low HOA",
    ],
    images: [
      "/images/properties/property-2.svg",
      "/images/properties/property-3.svg",
      "/images/properties/property-4.svg",
      "/images/properties/property-5.svg",
      "/images/properties/property-1.svg",
    ],
    lat: 40.3209,
    lng: -111.9734,
    daysOnMarket: 6,
    hoaFees: 140,
    garage: 2,
    stories: 2,
    listDate: "2026-02-25",
    agent: "David Childs",
  },
  {
    mlsNumber: "MLS-100038",
    slug: "",
    address: "200 E 1600 S",
    city: "Springville",
    state: "UT",
    zipCode: "84663",
    price: 480000,
    beds: 4,
    baths: 3,
    sqft: 2500,
    lotSize: "0.22 acres",
    yearBuilt: 2015,
    propertyType: "Single Family",
    status: "Pending",
    description:
      "Lovely Springville home near Hobble Creek Canyon with a park-like backyard. Open main level with a gas fireplace, built-in entertainment center, and an oversized garage perfect for a workshop. The finished basement features a large rec room and extra bedroom.",
    features: [
      "Gas Fireplace",
      "Entertainment Center",
      "Oversized Garage",
      "Workshop Space",
      "Rec Room",
      "Park-Like Yard",
      "3-Car Garage",
      "Storage Room",
    ],
    images: [
      "/images/properties/property-3.svg",
      "/images/properties/property-4.svg",
      "/images/properties/property-5.svg",
      "/images/properties/property-1.svg",
      "/images/properties/property-2.svg",
    ],
    lat: 40.1518,
    lng: -111.6028,
    daysOnMarket: 15,
    garage: 3,
    stories: 2,
    listDate: "2026-02-16",
    agent: "David Childs",
  },
  {
    mlsNumber: "MLS-100039",
    slug: "",
    address: "300 W Maple Ave",
    city: "Mapleton",
    state: "UT",
    zipCode: "84664",
    price: 789000,
    beds: 5,
    baths: 3.5,
    sqft: 3800,
    lotSize: "0.50 acres",
    yearBuilt: 2010,
    propertyType: "Single Family",
    status: "Active",
    description:
      "Charming Mapleton home on a half-acre lot with mature maples lining the driveway. Country-style kitchen with butcher block island, a cozy reading nook, and an expansive deck overlooking the garden. Detached workshop with power and lighting.",
    features: [
      "Butcher Block Island",
      "Reading Nook",
      "Expansive Deck",
      "Garden",
      "Detached Workshop",
      "Mature Trees",
      "3-Car Garage",
      "Irrigation Water",
    ],
    images: [
      "/images/properties/property-4.svg",
      "/images/properties/property-5.svg",
      "/images/properties/property-1.svg",
      "/images/properties/property-2.svg",
      "/images/properties/property-3.svg",
    ],
    lat: 40.1295,
    lng: -111.5873,
    daysOnMarket: 20,
    garage: 3,
    stories: 2,
    listDate: "2026-02-11",
    agent: "David Childs",
  },
  {
    mlsNumber: "MLS-100040",
    slug: "",
    address: "500 E 300 S Unit 7",
    city: "Salt Lake City",
    state: "UT",
    zipCode: "84102",
    price: 465000,
    beds: 2,
    baths: 2,
    sqft: 1250,
    lotSize: "N/A",
    yearBuilt: 2019,
    propertyType: "Condo",
    status: "Active",
    description:
      "Chic Salt Lake City condo in the trendy 9th and 9th neighborhood. Industrial-modern design with exposed ductwork, polished concrete floors, and a private rooftop terrace. Walk to boutiques, cafes, and Liberty Park.",
    features: [
      "Rooftop Terrace",
      "Exposed Ductwork",
      "Polished Concrete",
      "Industrial Design",
      "Walk to Shops",
      "Secure Entry",
      "Bike Storage",
      "1 Parking Space",
    ],
    images: [
      "/images/properties/property-5.svg",
      "/images/properties/property-1.svg",
      "/images/properties/property-2.svg",
      "/images/properties/property-3.svg",
      "/images/properties/property-4.svg",
    ],
    lat: 40.7480,
    lng: -111.8672,
    daysOnMarket: 12,
    hoaFees: 400,
    garage: 0,
    stories: 1,
    listDate: "2026-02-19",
    agent: "David Childs",
  },
  {
    mlsNumber: "MLS-100041",
    slug: "",
    address: "6000 N Highland Blvd",
    city: "Highland",
    state: "UT",
    zipCode: "84003",
    price: 835000,
    beds: 5,
    baths: 3.5,
    sqft: 4000,
    lotSize: "0.45 acres",
    yearBuilt: 2015,
    propertyType: "Single Family",
    status: "Active",
    description:
      "Immaculate Highland home in the Beacon Hills community with a park-like setting. Features a bright white kitchen with apron-front sink, shiplap accent walls, and a main-level office. The backyard includes a built-in trampoline, swing set, and covered pavilion.",
    features: [
      "Apron-Front Sink",
      "Shiplap Walls",
      "Main Level Office",
      "Built-In Trampoline",
      "Covered Pavilion",
      "Swing Set",
      "3-Car Garage",
      "Community Park",
    ],
    images: [
      "/images/properties/property-1.svg",
      "/images/properties/property-2.svg",
      "/images/properties/property-3.svg",
      "/images/properties/property-4.svg",
      "/images/properties/property-5.svg",
    ],
    lat: 40.4355,
    lng: -111.7896,
    daysOnMarket: 9,
    garage: 3,
    stories: 2,
    listDate: "2026-02-22",
    agent: "David Childs",
  },
  {
    mlsNumber: "MLS-100042",
    slug: "",
    address: "1234 W Pioneer Crossing",
    city: "Lehi",
    state: "UT",
    zipCode: "84043",
    price: 449000,
    beds: 3,
    baths: 2.5,
    sqft: 2000,
    lotSize: "0.12 acres",
    yearBuilt: 2022,
    propertyType: "Townhouse",
    status: "Active",
    description:
      "Desirable Lehi townhome at the crossroads of Silicon Slopes. Open concept with 9-foot ceilings, a sleek kitchen with waterfall island, and a spacious loft. Walking distance to shops, restaurants, and the Frontrunner station.",
    features: [
      "Waterfall Island",
      "9-Foot Ceilings",
      "Loft Space",
      "Near Frontrunner",
      "Walk to Shops",
      "Patio",
      "2-Car Garage",
      "Smart Locks",
    ],
    images: [
      "/images/properties/property-2.svg",
      "/images/properties/property-3.svg",
      "/images/properties/property-4.svg",
      "/images/properties/property-5.svg",
      "/images/properties/property-1.svg",
    ],
    lat: 40.3945,
    lng: -111.8487,
    daysOnMarket: 5,
    hoaFees: 210,
    garage: 2,
    stories: 2,
    listDate: "2026-02-26",
    agent: "David Childs",
  },
  {
    mlsNumber: "MLS-100043",
    slug: "",
    address: "2800 N 600 W",
    city: "Pleasant Grove",
    state: "UT",
    zipCode: "84062",
    price: 545000,
    beds: 4,
    baths: 3,
    sqft: 2700,
    lotSize: "0.21 acres",
    yearBuilt: 2017,
    propertyType: "Single Family",
    status: "Active",
    description:
      "Modern Pleasant Grove home with a functional layout perfect for families. Large kitchen with pantry, a bonus loft upstairs, and a fully finished basement with plumbing roughed in for a future kitchenette. The backyard features a gas fire pit and concrete patio.",
    features: [
      "Bonus Loft",
      "Walk-In Pantry",
      "Gas Fire Pit",
      "Concrete Patio",
      "Finished Basement",
      "Future Kitchenette",
      "2-Car Garage",
      "Energy Star",
    ],
    images: [
      "/images/properties/property-3.svg",
      "/images/properties/property-4.svg",
      "/images/properties/property-5.svg",
      "/images/properties/property-1.svg",
      "/images/properties/property-2.svg",
    ],
    lat: 40.3721,
    lng: -111.7466,
    daysOnMarket: 18,
    garage: 2,
    stories: 2,
    listDate: "2026-02-13",
    agent: "David Childs",
  },
  {
    mlsNumber: "MLS-100044",
    slug: "",
    address: "Lot 15 Box Elder Ln",
    city: "Alpine",
    state: "UT",
    zipCode: "84004",
    price: 450000,
    beds: 0,
    baths: 0,
    sqft: 0,
    lotSize: "1.5 acres",
    yearBuilt: 0,
    propertyType: "Land",
    status: "Active",
    description:
      "Rare 1.5-acre building lot in Alpine with breathtaking views of Lone Peak, Box Elder Peak, and the surrounding valley. Utilities stubbed to the lot line. Perfect for your custom dream home in one of Utah County's most desirable communities.",
    features: [
      "Mountain Views",
      "Utilities Available",
      "1.5 Acres",
      "Custom Home Site",
      "Paved Road",
      "Gentle Slope",
      "No HOA",
    ],
    images: [
      "/images/properties/property-4.svg",
      "/images/properties/property-5.svg",
      "/images/properties/property-1.svg",
      "/images/properties/property-2.svg",
      "/images/properties/property-3.svg",
    ],
    lat: 40.4583,
    lng: -111.7621,
    daysOnMarket: 55,
    garage: 0,
    stories: 0,
    listDate: "2026-01-07",
    agent: "David Childs",
  },
  {
    mlsNumber: "MLS-100045",
    slug: "",
    address: "900 W 800 N",
    city: "Spanish Fork",
    state: "UT",
    zipCode: "84660",
    price: 420000,
    beds: 4,
    baths: 2,
    sqft: 2100,
    lotSize: "0.19 acres",
    yearBuilt: 2008,
    propertyType: "Single Family",
    status: "Active",
    description:
      "Solid Spanish Fork home in a great neighborhood near Salem Pond and walking trails. Open living and dining area, a large master bedroom, and a nicely landscaped yard with drip irrigation. Quick access to I-15 for commuters heading north.",
    features: [
      "Open Living Area",
      "Drip Irrigation",
      "Near Trails",
      "Landscaped Yard",
      "New Paint",
      "Central Air",
      "2-Car Garage",
      "Close to I-15",
    ],
    images: [
      "/images/properties/property-5.svg",
      "/images/properties/property-1.svg",
      "/images/properties/property-2.svg",
      "/images/properties/property-3.svg",
      "/images/properties/property-4.svg",
    ],
    lat: 40.1202,
    lng: -111.6488,
    daysOnMarket: 31,
    garage: 2,
    stories: 2,
    listDate: "2026-01-31",
    agent: "David Childs",
  },
  {
    mlsNumber: "MLS-100046",
    slug: "",
    address: "1456 E 450 S",
    city: "Lindon",
    state: "UT",
    zipCode: "84042",
    price: 675000,
    beds: 5,
    baths: 3,
    sqft: 3300,
    lotSize: "0.30 acres",
    yearBuilt: 2014,
    propertyType: "Single Family",
    status: "Coming Soon",
    description:
      "Beautifully maintained Lindon home in the desirable Fieldstone neighborhood. Features a bright, open main level with a butler's pantry, a spacious master suite with soaking tub, and a finished walkout basement. The private backyard backs up to Lindon City Trail.",
    features: [
      "Butler's Pantry",
      "Soaking Tub",
      "Walkout Basement",
      "Trail Access",
      "Private Backyard",
      "Crown Molding",
      "3-Car Garage",
      "Wired for Surround Sound",
    ],
    images: [
      "/images/properties/property-1.svg",
      "/images/properties/property-2.svg",
      "/images/properties/property-3.svg",
      "/images/properties/property-4.svg",
      "/images/properties/property-5.svg",
    ],
    lat: 40.3387,
    lng: -111.7180,
    daysOnMarket: 0,
    garage: 3,
    stories: 2,
    listDate: "2026-03-05",
    agent: "David Childs",
  },
  {
    mlsNumber: "MLS-100047",
    slug: "",
    address: "456 W 200 N",
    city: "American Fork",
    state: "UT",
    zipCode: "84003",
    price: 589000,
    beds: 4,
    baths: 3,
    sqft: 2800,
    lotSize: "0.23 acres",
    yearBuilt: 2019,
    propertyType: "Single Family",
    status: "Active",
    description:
      "Attractive American Fork two-story with a thoughtful floor plan and premium upgrades. White cabinets, quartz countertops, and a tile backsplash give the kitchen a modern feel. The finished basement includes a large family room and a dedicated exercise area.",
    features: [
      "White Cabinets",
      "Quartz Countertops",
      "Tile Backsplash",
      "Exercise Area",
      "Family Room",
      "Finished Basement",
      "2-Car Garage",
      "Full Landscaping",
    ],
    images: [
      "/images/properties/property-2.svg",
      "/images/properties/property-3.svg",
      "/images/properties/property-4.svg",
      "/images/properties/property-5.svg",
      "/images/properties/property-1.svg",
    ],
    lat: 40.3799,
    lng: -111.7988,
    daysOnMarket: 7,
    garage: 2,
    stories: 2,
    listDate: "2026-02-24",
    agent: "David Childs",
  },
  {
    mlsNumber: "MLS-100048",
    slug: "",
    address: "123 E 100 N",
    city: "Provo",
    state: "UT",
    zipCode: "84606",
    price: 650000,
    beds: 4,
    baths: 2,
    sqft: 2400,
    lotSize: "0.30 acres",
    yearBuilt: 1940,
    propertyType: "Multi-Family",
    status: "Active",
    description:
      "Excellent investment opportunity in Provo near BYU campus. This duplex features two well-maintained 2-bed/1-bath units with separate entrances, individual meters, and consistent rental history. Strong cash flow with below-market rents and room for increases.",
    features: [
      "Duplex",
      "Separate Entrances",
      "Individual Meters",
      "Rental Income",
      "Near BYU",
      "Off-Street Parking",
      "Coin Laundry",
      "Landscaped",
    ],
    images: [
      "/images/properties/property-3.svg",
      "/images/properties/property-4.svg",
      "/images/properties/property-5.svg",
      "/images/properties/property-1.svg",
      "/images/properties/property-2.svg",
    ],
    lat: 40.2418,
    lng: -111.6552,
    daysOnMarket: 40,
    garage: 0,
    stories: 2,
    listDate: "2026-01-22",
    agent: "David Childs",
  },
  {
    mlsNumber: "MLS-100049",
    slug: "",
    address: "Lot 8 Mountain Vista Rd",
    city: "Draper",
    state: "UT",
    zipCode: "84020",
    price: 625000,
    beds: 0,
    baths: 0,
    sqft: 0,
    lotSize: "0.75 acres",
    yearBuilt: 0,
    propertyType: "Land",
    status: "Active",
    description:
      "Premium 0.75-acre building lot in Draper's exclusive SunCrest development with panoramic views of the Salt Lake Valley. All utilities in place, including natural gas and fiber internet. Build your dream home with unmatched sunset views.",
    features: [
      "Valley Views",
      "All Utilities",
      "Fiber Internet",
      "0.75 Acres",
      "Paved Roads",
      "SunCrest Community",
      "Hiking Trails",
      "No Time Limit to Build",
    ],
    images: [
      "/images/properties/property-4.svg",
      "/images/properties/property-5.svg",
      "/images/properties/property-1.svg",
      "/images/properties/property-2.svg",
      "/images/properties/property-3.svg",
    ],
    lat: 40.5280,
    lng: -111.8510,
    daysOnMarket: 48,
    hoaFees: 150,
    garage: 0,
    stories: 0,
    listDate: "2026-01-14",
    agent: "David Childs",
  },
  {
    mlsNumber: "MLS-100050",
    slug: "",
    address: "2500 N 1200 W",
    city: "Saratoga Springs",
    state: "UT",
    zipCode: "84045",
    price: 510000,
    beds: 4,
    baths: 2.5,
    sqft: 2600,
    lotSize: "0.15 acres",
    yearBuilt: 2024,
    propertyType: "Single Family",
    status: "Active",
    description:
      "Brand-new Saratoga Springs home in the Jordan View community with modern finishes and an efficient layout. Features include a large kitchen island, dedicated home office nook, and a fully fenced backyard with a concrete patio. Community boat ramp access to Utah Lake.",
    features: [
      "Kitchen Island",
      "Home Office Nook",
      "Fenced Yard",
      "Concrete Patio",
      "Boat Ramp Access",
      "Community Pool",
      "2-Car Garage",
      "Energy Efficient",
    ],
    images: [
      "/images/properties/property-5.svg",
      "/images/properties/property-1.svg",
      "/images/properties/property-2.svg",
      "/images/properties/property-3.svg",
      "/images/properties/property-4.svg",
    ],
    lat: 40.3551,
    lng: -111.8978,
    daysOnMarket: 2,
    hoaFees: 110,
    garage: 2,
    stories: 2,
    listDate: "2026-03-01",
    agent: "David Childs",
  },
];

// Generate slugs for all properties
MOCK_PROPERTIES.forEach((property) => {
  property.slug = generateSlug(property.address, property.mlsNumber);
});

export class MockMLSAdapter implements MLSAdapter {
  private properties: Property[] = MOCK_PROPERTIES;

  async searchProperties(
    params: PropertySearchParams
  ): Promise<PropertySearchResult> {
    let filtered = [...this.properties];

    // Text search across address, city, description, and features
    if (params.query) {
      const q = params.query.toLowerCase();
      filtered = filtered.filter(
        (p) =>
          p.address.toLowerCase().includes(q) ||
          p.city.toLowerCase().includes(q) ||
          p.description.toLowerCase().includes(q) ||
          p.features.some((f) => f.toLowerCase().includes(q)) ||
          p.mlsNumber.toLowerCase().includes(q)
      );
    }

    // Filter by city
    if (params.city) {
      filtered = filtered.filter(
        (p) => p.city.toLowerCase() === params.city!.toLowerCase()
      );
    }

    // Filter by property type
    if (params.propertyType) {
      filtered = filtered.filter(
        (p) => p.propertyType === params.propertyType
      );
    }

    // Filter by status
    if (params.status) {
      filtered = filtered.filter((p) => p.status === params.status);
    }

    // Filter by price range
    if (params.minPrice !== undefined) {
      filtered = filtered.filter((p) => p.price >= params.minPrice!);
    }
    if (params.maxPrice !== undefined) {
      filtered = filtered.filter((p) => p.price <= params.maxPrice!);
    }

    // Filter by beds
    if (params.minBeds !== undefined) {
      filtered = filtered.filter((p) => p.beds >= params.minBeds!);
    }

    // Filter by baths
    if (params.minBaths !== undefined) {
      filtered = filtered.filter((p) => p.baths >= params.minBaths!);
    }

    // Filter by sqft range
    if (params.minSqft !== undefined) {
      filtered = filtered.filter((p) => p.sqft >= params.minSqft!);
    }
    if (params.maxSqft !== undefined) {
      filtered = filtered.filter((p) => p.sqft <= params.maxSqft!);
    }

    // Sort
    switch (params.sort) {
      case "newest":
        filtered.sort(
          (a, b) =>
            new Date(b.listDate).getTime() - new Date(a.listDate).getTime()
        );
        break;
      case "price-asc":
        filtered.sort((a, b) => a.price - b.price);
        break;
      case "price-desc":
        filtered.sort((a, b) => b.price - a.price);
        break;
      case "beds":
        filtered.sort((a, b) => b.beds - a.beds);
        break;
      case "sqft":
        filtered.sort((a, b) => b.sqft - a.sqft);
        break;
      default:
        // Default sort by newest
        filtered.sort(
          (a, b) =>
            new Date(b.listDate).getTime() - new Date(a.listDate).getTime()
        );
    }

    // Pagination
    const page = params.page || 1;
    const limit = params.limit || 12;
    const total = filtered.length;
    const totalPages = Math.ceil(total / limit);
    const start = (page - 1) * limit;
    const paged = filtered.slice(start, start + limit);

    return {
      properties: paged,
      total,
      page,
      totalPages,
    };
  }

  async getProperty(mlsNumber: string): Promise<Property | null> {
    return (
      this.properties.find((p) => p.mlsNumber === mlsNumber) || null
    );
  }

  async getFeaturedProperties(limit: number = 6): Promise<Property[]> {
    return this.properties
      .filter((p) => p.status === "Active")
      .slice(0, limit);
  }

  async getSimilarProperties(
    property: Property,
    limit: number = 4
  ): Promise<Property[]> {
    return this.properties
      .filter(
        (p) =>
          p.mlsNumber !== property.mlsNumber &&
          p.status === "Active" &&
          (p.city === property.city || p.propertyType === property.propertyType)
      )
      .sort((a, b) => {
        // Prioritize same city
        const aCity = a.city === property.city ? 1 : 0;
        const bCity = b.city === property.city ? 1 : 0;
        if (aCity !== bCity) return bCity - aCity;

        // Then prioritize similar price (within 30%)
        const aPriceDiff = Math.abs(a.price - property.price) / property.price;
        const bPriceDiff = Math.abs(b.price - property.price) / property.price;
        return aPriceDiff - bPriceDiff;
      })
      .slice(0, limit);
  }

  async getCities(): Promise<string[]> {
    const cities = new Set(this.properties.map((p) => p.city));
    return Array.from(cities).sort();
  }
}
